### ISSUE TITLE
plot_proc.py fail if radial thickness set to 0

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1091]
In GitLab by @asbrown on Aug 19, 2020, 22:24

## Summary

In plot_proc.py the radial build has a variable calculated called `rminx` which has equations of the following form:

`rminx = (cumulative_radial_build("shldoth", mfile_data, scan) - cumulative_radial_build("ddwi", mfile_data, scan)) / 2.0`<br><br>

The function `cumulative_radial_build()` will calculate the radial distance of the component (e.g. `ddwi`) and the variable `rminx` is subsequently used in the equation:

`kapx = cumulative_lower['shldoth'] / rminx`<br><br>

The equation for `kapx` will fall over if `rminx = 0`, and this can happen if the second radial component is equal to 0 (e.g. `ddwi`), which would mean:

`cumulative_radial_build("shldoth", mfile_data, scan) = cumulative_radial_build("ddwi", mfile_data, scan)`<br><br>

Although not an issue for conventional tokamaks, a spherical tokamak will have an inboard vacuum vessel thickness (`ddwi`) of 0 since there are designs with no inboard vacuum vessel.

There are four instances of this `rminx` being calculated with the following input variables:

- `ddwo` & `gapds`
- `shldoth` & `ddwi`
- `shldoth` & `ddwi`
- `vvblgapo` & `shldith`

[plot_proc.py](https://git.ccfe.ac.uk/process/process/uploads/57bbef40a8afddd94ad316e0af3b45bc/plot_proc.py)

## Proposed Solution

Have an additional check that bypasses the equation if `rminx` becomes 0.

## Checklist

* [ ] Run plot_proc.py
* [ ] Run test suite
* [ ] Does it change the baseline 2019 run?
* [ ] Merge request created

**Comment by kj5248** [comment]
Equations now handled differently such that a component having no thickness will not cause errors to occur. However if you set a component such as vacuum vessel inboard thickness to 0 it will not remove it as a plotting option. Instead it will have 0 thickness at z=0 on the inboard side and increase as r increases, until it reaches the thickness of the vacuum vessel at the outboard side.

Currently this is not reflected in the poloidal cross section due to issues with matplotlib's fill (issue #3250).
