### ISSUE TITLE
Resistive magnets mass flow rates

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1143]
In GitLab by @skahn on Oct 14, 2020, 12:43

## Description

The mass flow rate of the TF magnet coolant can be a design constraint. 

## Proposal 

Add a constraint equation on the mass flow rate.

Best regards     
Sebastien Kahn

**Comment by j-a-foster** [comment]
Looked in the code and the only place that TF coil coolant velocity/mass flow rate is in `cntrpst` in `tfcoil.py`. This function is only called for spherical tokamaks so the constraint equation wouldn't apply in general.

Spoke to @mkovari and due to the above and a lack of priority for this to be added, I'm closing the issue.
