### ISSUE TITLE
Assymetric DEMO insertion gap

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1288]
In GitLab by @skahn on Mar 19, 2021, 09:53

## Description

For EU-DEMO the TF WP cross-section was defined in a slightly different way to how PROCESS (around 2015) handled it. The ground insulation (at the time 8 mm) was to be wrapped around the winding pack. The winding pack was then to be inserted (during manufacture) inside the steel casing (which comes in several parts). The plasma-facing "front" casing was then to be welded onto the rest of the casing (again in multiple parts), thus enclosing the winding pack in the steel structure. Due to inevitable manufacturing tolerances of such large components, it was deemed necessary to include what was called an insertion gap (10 mm at the time). The resulting void was to be filled by introducing a liquid resin which would later be cured. It was felt that the insertion gap on the inboard was going to be predominantly to one side in the radial direction. I'm fairly sure that the WP was to be more or less flush to the inboard casing (including the ground insulation) and that the insertion gap was to lie on the outer edge of the inboard winding pack.

This assymetric insertion gap should probably be implemented.

**Comment by mkovari** [comment]
Hi @cjwgriesel Charles, 
I have a feeling that you are overthinking this issue.  If you want to tackle this issue now, as suggested by the Papercuts assignment, it would be best not to try to solve everything esle at the same time.  The thickness of the insulation gap around the winding pack ("ground insulation") can be dealt with in isolation.

Having said that, I am not sure this issue should be implemented at all.  

The first step is to find an up to date sketch of the TF coil cross-section, showing the insertion gap.  Then we can decide whether it needs changing.

**Comment by cjwgriesel** [comment]
real(dp) :: tfinsgap
  !! TF coil WP insertion gap (m)
Is the variable already assigned for the winding pack insertion gap within process. I am looking at the magnet dimensions which is inter related with the cable pack problem in fitting it within the magnet casing.

**Comment by cjwgriesel** [comment]
The variable already exists within the process code.
  real(dp) :: tfinsgap
  !! TF coil WP insertion gap (m)
And as this relates to the wider issue of magnet dimensions and fitting the cable pack within the inner leg of the magnet coil I think this is issue could be closed as it will be covered in the investigation of fitting the cable pack within in the magnet. If the cable pack fits within the winding pack space in the magnet how much extra space if any should be allowed for potting the winding pack? If it fits ok the potting compound will fill all exterior voids between the cable pack and the casing of the inner leg of the magnet.

**Comment by jonmaddock** [comment]
@cjwgriesel I'm not sure this issue should be closed. As @mkovari suggests, can't this issue be dealt with in isolation, without dealing with the larger wider problem? Can you link to the wider issue to help distinguish from this one? If this is too large a problem to be dealt with in a single papercut, what is the plan to resolve this?

**Comment by cjwgriesel** [comment]
The variable tfinsgap is applied on all fours sides of the WP area although this needs to be proved that is what is actually happening. In the solution it does have a value although how that occurs needs to be established. There are three places that tfinsgap is displayed in the OUT.DAT file and all three values are different!!!!!  In the original issue this gap was to be applied to the outer edge in the radial direction.  In the code if i_tf_turns_integer = 0 then the WP consist of non integer cables meaning that the winding pack consists of a soup of area fractions of the parameters that make up cables etc which is unrealistic. In this case I think the insertion gap is nonsense. The non-integer cables option was introduced to aid convergence. The realistic option is i_tf_turns_integer = 1 integer cables but that will make convergence more difficult as there are many conflicting requirements. The HTS coils have to be able to take the current, deliver a sufficiently powerful magnetic field, the cooling must be adequate, the steel casing has to take the structural loads, the insulation between cables and the magnet steel casing must be sufficient and the WP has to fit within the space provided inside the steel magnet casing. Additionally it is not known what gaps there will be around the four sides of a cable pack. The choice of 10mm on the outer edge of the WP seems to be somewhat arbitrary? Perhaps this comes down to not knowing the accuracy of manufacturing and what tolerance is to be allowed for fitting the coils within the steel casing? A fitting tolerance is needed which should be adjustable. But first I think the integer cable pack needs to be calculated correctly with the centre point position calculated for each cable so that the exact position of each cable is known and from that the space taken up by the WP. Initially only a rectangular space should be allowed for a cable pack made up of only square cables. That is the simplest option to first implement.

**Comment by chris-ashe** [comment]
After discussion with @mkovari we have decided that there is not much benefit with implementing this feature. As its effects will have a minuscule effect on the output. It is also still unknown about the WP insertion gap configuration gap for EU-DEMO so this may eventually become redundant.
