### ISSUE TITLE
The calculation for centrepost life is wrong when an inboard blanket is used. Needs fixing.

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1395]
In GitLab by @cjwgriesel on Sep 6, 2021, 09:44

**Comment by kj5248** [comment]
Blanket life is calculated from allowable fluence and mean wall load. This would not differ between an inboard or outboard blanket so not sure why it needs to be split up. For things like including extra detail to improve the accuracy ie account for things like thermal shield thickness would require some form of neutronics calculations. This could be done but is probably too complex for the slight difference it would make. This would only increase the length of the centrepost lifetime, so can just treat current case as a worst case lifetime. Therefore not sure anything actually needs to be done. Furthermore there is a newer model for centrepost lifetime that was made after this issue was created.
