### ISSUE TITLE
process_netcdf.py - not urgent

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#227]
In GitLab by @hlux on Mar 6, 2015, 09:06

When using evaluate_uncertainties.py or display_uncertainties.py and one of the output_vars is misspelled or not in the MFILE/netcdf file, the code does either stop or does not work properly. This can be quite an issue, for special cases where the actual name in the mfile object is not intuitive. Therefore, it can be very beneficial to have a list of suggestions that actually do exist in the mfile object. If everything from the MFILE would be suggested, this would be extremely long, so maybe everything matching one or two of the variables in the word should be matched. Of course this could be made a lot more sophisticated than this, but I think will not be necessary.

**Comment by clmould** [comment]
I've spoken with @timothy-nunn about this and we think this issue is not relevant any more. In looking into this papercut issue, it has been found that a large portion of the cdf code in PROCESS is no longer being used, and an issue has been created to review this and decide if it needs removing from PROCESS: #3072
