### ISSUE TITLE
Remove duplicate push and PR jobs in CI

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#3159]
When pushing to branch with an associated PR, all jobs are duplicated for the `push` and `pull_request` events. Could we just run each job once?

**Comment by timothy-nunn** [comment]
Hi @jonmaddock,

I believe these jobs have a place in our CI. The PR jobs run the code in the state it will be post-merge (if the PR was merged into main this second). As such we have cases as follow:

![image](https://github.com/ukaea/PROCESS/assets/75321887/c398da9a-9e37-4906-925c-d6e23dfc529b)

Where the PR jobs fail (in this case, its because `main` is currently failing due to #3204). In my opinion, this is another tool to help us identify changes made since the 'branch off' of main that will interact with a feature branch to cause PROCESS to fail.

**Comment by jonmaddock** [comment]
Thanks for explaining that to me Tim; I was aware of this functionality, but I didn't know that's what the `pull_request` job corresponded to: I just thought that was triggering a "regular" CI run. Great!
