### ISSUE TITLE
Olivier Sauter's formulae including negative triangularity

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#392]
In GitLab by @hlux on Jun 2, 2016, 10:42

Please include Oliviers new formula in PROCESS, so that we can run comparisons with M. Kikuchi's suggested reactor version.

**Comment by mkovari** [comment]
The reactor parameters for Kikuchi's negative triangularity configuration, using Sauter's new formulae valid for negative delta, are given on pp 40-41 of the link above.

**Comment by mkovari** [comment]
`qpsi     : input real :  plasma edge safety factor (= q-bar for icurr=2)`
In the calling function we find `physics_variables.q`.  This is passed to `culcur` where it is named `qpsi` for some reason.  This is consistent with the documentation:

q | Input | real | 3.0 | Safety factor 'near' plasma edge (iteration variable 18) equal to q95  (unless icurr=2 (ST current scaling), in which case q = mean edge safety factor qbar)
-- | -- | -- | -- | --

- [ ] Update docstring in `culcur`.
- [ ] Rename `qpsi` in `culcur` as `q95`.
- [ ] Eliminate `curhat` since it's not necessary.
- [ ] Test for a range of values of triangularity $\delta$.

**Comment by mkovari** [comment]
When the triangularity is negative, the vacuum vessel may clash with the TF coil, not surprisingly:
![image](https://github.com/ukaea/PROCESS/assets/9718416/2ecf5f15-f9fc-491f-aa4e-a8c63154086b)
I have not attempted to fix this.

**Comment by mkovari** [comment]
Unfortunately, Kikuchi's presentation doesn't clearly give the values of elongation or triangularity, so I can't use it for benchmarking.  I won't be able to do a quantitative check on the geometric formulae.

I will try a qualitative check, using two runs with triangularity of opposite sign.  

- The poloidal perimeter is the same, because the formula contains only $\delta^2$.  
- The cross-section is also the same, because the formula doesn't include $\delta$ at all.
- The surface area and volume are bigger for negative $\delta$, because the mean radius is bigger - the plasma is further from the axis on average.

This seems OK.

  |   | Negative | Positive |  
-- | -- | -- | -- | --
Major radius (m) | (rmajor) | 8 | 8 | ITV
Minor radius (m) | (rminor) | 2.667 | 2.667 | OP
Aspect ratio | (aspect) | 3 | 3 |  
Elongation, X-point (input value used) | (kappa) | 1.85 | 1.85 | IP
Elongation, 95% surface (calculated from   kappa) | (kappa95) | 1.652 | 1.652 | OP
Elongation, area ratio calc. | (kappaa) | 1.85 | 1.85 | OP
Triangularity, X-point (input value used) | (triang) | -0.5 | 0.5 | IP
Triangularity, 95% surface (calculated   from triang) | (triang95) | -0.333 | 0.333 | OP
Plasma poloidal perimeter (m) | (pperim) | 25.08 | 25.08 | OP
Plasma cross-sectional area (m2) | (xarea) | 41.329 | 41.329 | OP
Plasma surface area (m2) | (sarea) | 1.33E+03 | 1.19E+03 | OP
Plasma volume (m3) | (vol) | 2.16E+03 | 1.99E+03 | OP

**Comment by mkovari** [comment]
Sauter also gives a formula for the trapped fraction, using [ref 16 ](http://infoscience.epfl.ch/record/187521).   Although it looks simple, the reference doesn't seem to make sense.  The point corresponding to the plasma edge ($\epsilon=0.32$) in Fig 6(a) gives values of trapped fraction which don't agree with the fitting formula (0.746 for $\delta=0.5$ and 0.824 for $\delta=-0.5$).

I have *not* implemented the formula for trapped fraction.

**Comment by mkovari** [comment]
I have used Sauter's formulae only for the *edge* parameters.  I think they should work for every flux surface, but one would need to know the values of $\kappa, \delta$ and $\epsilon$ at each flux surface, which we don't have in Process.
