### ISSUE TITLE
Error handling for negative conductor fraction in TF cable

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#537]
In GitLab by @jmorris-uk on Jul 20, 2017, 10:24

When running the attached file the conductor fraction in the TF coil cable, `fcond` becomes negative and PROCESS exits.

The runs that produced this error are using a fixed lower bound on `flhthresh`.

Error message currently says

```
ERROR
Negative Iop/Icrit for TF coil
jsc  -10422953815.083780
iooic  -646.60798298979466
jcritsc   16119432.622668818
Check cable dimensions. fcond likely gone negative. fcond = -0.21675003606880239
```

**Comment by clmould** [comment]
@ajpearcey @jmorris-uk I can't get this input file to run, do you know if there's an input file that this issue still occurs on?

**Comment by ajpearcey** [comment]
this very unconstrained input file will throw the error, but without `fcond` becoming negative, but simply because several of the current constraints are not switched on (icc = 33, 35) 
[IN.DAT.TXT](https://github.com/ukaea/PROCESS/files/14509063/IN.DAT.TXT)

**Comment by clmould** [comment]
In sctfcoil.py there is already a 'guard against negative conductor fraction fcond' which is a kludge to prevent fcond from being negative, and so the current error message needs changing since fcond cannot be negative now.
However, for the new input file the error is still thrown but this is now because acs is calculated to be negative (and this is because t_cable_radial is calculated to be < 0).
For this papercut issue, I have edited the error message to say `acs likely gone negative` instead of `fcond likely gone negative`. However this has shown a different problem in the code where acs is calculated to be negative and so this needs discussing (in the process development meeting) and will be fixed in a new issue
