### ISSUE TITLE
Warnings for function ncore

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#736]
In GitLab by @stuartmuldrew on Jul 9, 2018, 08:32

The function ncore in plasma_profiles.f90 calculates the central density of a pedestal profile, however there is currently no warning if the central density is less than the pedestal density.  Additionally, under certain situations it returns a negative central density without stopping.  I will add a warning to the error list.

**Comment by mkovari** [comment]
This problem raised its head again in December 2023:
------------------------------------------------------

The graph shows ncore as a function of nsep, for different values of nped.  
n.0 does indeed go negative, but only when nped > n.av

n.0 is greater than n.av except when n.ped=n.av

The whole problem arises because we have the option of setting n.ped and n.sep in terms of the Greenwald density, but we don’t do the same with n.av.

![image](https://github.com/ukaea/PROCESS/assets/9718416/bec12590-cc17-412a-8aae-f01d0e7f652e)
![image](https://github.com/ukaea/PROCESS/assets/9718416/8416944c-697f-4815-b703-4c4ab783cace)
![image](https://github.com/ukaea/PROCESS/assets/9718416/6332d90e-9b74-452f-9197-1fbae8c6c23e)
There is a minus sign here.

You may notice that my paper doesn’t give any references for this formula, but I don’t know why.  We may need to ask Hanni for the reference.

I though the reference might be the attached paper.   However, the formula there looks very different:

![image](https://github.com/ukaea/PROCESS/assets/9718416/fe435cc9-7e68-41f5-aa3c-e270b9bd6d4f)
where Theta1 and Gamma1 are given by separate formulae.

[Johner_2010_HELIOS.pdf](https://github.com/ukaea/PROCESS/files/12583809/Johner_2010_HELIOS.pdf)

**Comment by mkovari** [comment]
This issue was originally raised by Stuart but it doesn't seem that Seb fixed it fully since Jon discovered the same problem in December 2022.  I have reopened it, leaving it as an issue (rather than a discussion) as it is a bug rather than a feature request.  @jonmaddock @jmorris-uk

**Comment by chris-ashe** [comment]
I have made a quick plotting tool that allows all of the profile and pedestal values to be played around with so that it is easier to see how the negative central density problem comes about.
https://www.desmos.com/calculator/l9d9vtuzqe

A quick look from a file that presents such warnings shows that raising the lower limit of `dene` quickly pushes the solver away from a low enough value that `ncore` will never become negative.

A possible quick fix solution would be just to warn the user to raise the lower limit of `dene`

**Comment by mkovari** [comment]
Can you suggest a value for the lower bound of `dene`?  For example, if you expect that the converged solution will have volume-averaged electron density `dene`~1e20 m-3 then set the lower bound to 8e19?

Also recommend that people use constraint number 81.

**Comment by chris-ashe** [comment]
@mkovari 
Can easily be done. Though will need to have some margin as $n_{\text{ped}}$ and $n_{\text{sep}}$ can be iterated as well during a run and have influence on `ncore`. It would be best to present it as a warning and not enforce it internally to prevent how the profiles are solved becoming a black box.

Will also have a look at the `ncore` value that is enforced at the moment as it is re-set to 1E-6 if it becomes negative. Will see if pushing it back up to normal central density values pushes it back into the right direction for solving

**Comment by mkovari** [comment]
So can you suggest the lower bound as a fraction of the expected value of `dene`?  I just gave 80% as an example.

I definitely don't like the 1E-6 kludge.

**Comment by chris-ashe** [comment]
Two possible solutions at the moment, one quick fix and one long  term

**Quick Fix**
If `ncore` ever goes to zero or negative raise a level 2/3 error asking the user the please raise their lower limit of `dene` to prevent `ncore` going negative. This still allows full control and prevents implementing a black box solution

**Long term**
Invert the solving of `ncore` and have it as an iteration variable instead of `dene` . With `dene` instead being calculated for. Thus the lower bound of `ncore` could be specified to never go near zero. This will need to be stated clearly as `ncore` and `dene` cannot be iteration variables at the same time

**Comment by mkovari** [comment]
Qick fix - yes, so what lower bound do you suggest?

Long term. You pointed out that we often want to match a published scenario with specified volume-averaged density, so Option 2 may not be ideal.  However, it is certainly an option, and if we really want to we could add a constraint for a specified value of `dene`.

**Comment by mkovari** [comment]
We do already have a check at initialisation:
https://github.com/ukaea/PROCESS/blob/a4220251bff3ffeab70f5546d83d140b86494c60/source/fortran/initial.f90#L431-L436

This prints the following messages:
```json
      "no": 154,
      "level": 2,
      "message": "CHECK: neped set with fgwped without constraint eq 81 (neped<ne0)"

      "no": 155,
      "level": 2,
      "message": "CHECK: dene used as iteration variable without constraint 81 (neped<ne0)"
```

**Comment by mkovari** [comment]
Compare this density issue with a similar problem that can arise with temperature, for which we do have a check at initialisaton:
https://github.com/ukaea/PROCESS/blob/a4220251bff3ffeab70f5546d83d140b86494c60/source/fortran/initial.f90#L384-L410

**Comment by mkovari** [comment]
It is true that there are papers claiming that stable H mode can be obtained as long as ne,sep  ≤  nGW/2.  However, this is the outer midplane density.  I don't think this is representative of the average density over the separatrix.  This is not something we have ever discussed, really.  But if you need to then obviously go ahead and make sure the default bounds are high enough to permit the regression test to run without modification.

As you recall there are several other options available.
