### ISSUE TITLE
Double counting between bootstrap and beam driven currents

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#754]
In GitLab by @hlux on Aug 22, 2018, 08:57

From Richard:
>>>
I got this reply to a comment/question I made reviewing a paper on the subject of fast-ion pressure contributions to the bootstrap current:

“In principle the fast ion beta does contribute to the bootstrap current. Analytic expressions have been derived for beam ions [e.g., Taguchi1996] and alpha particles [e.g., Hsu1992]. The beam-ion bootstrap current depends on the toroidal injection angle and the ratio of the critical velocity to the birth velocity. For perpendicular injection, Taguchi calculated that the beam-ion bootstrap current is 9% of the bulk (i.e., thermal) bootstrap current at the same pressure gradient. In this paper, these analytic expressions are not utilized, however, as the current 
drive determined by the orbit-following Monte Carlo code NUBEAM includes all sources of fast-ion current. That is, NUBEAM does not distinguish between what we might call NBCD and what we might call fast-ion bootstrap current."

In other words, we may be making an erroneous division between beam-driven current and beta-driven bootstrap current, if in PROCESS we scale the beam-driven current to match the output of e.g. NUBEAM. So the bootstrap model in PROCESS – if this is the case – should include contributions from fusion-born alphas, but not from auxiliary-power driven fast ions IF the NUBEAM approach is generalised across the current drive codes we benchmark against. We should be careful not to double-count current contributions.

This may help explain some of the past discrepancies between the PROCESS bootstrap model and other models.
>>>

@mkovari , @jmorris-uk , @stuartmuldrew and @kellis (for your information and to keep in mind, when we are implementing any new beam models into e.g. PLASMOD, because I don't know when we would have benchmarked against NUBEAM in the past.)

**Comment by mkovari** [comment]
There are actually two separate topics here.

1. Does the Process bootstrap model include contributions from fusion-born alphas, and should it?  I suspect the answer is no, since the alphas don't explicitly contribute to the temperature and density distributions (although you could say they are included if you wanted to).
2. Does the Process bootstrap model include contributions from auxiliary-power driven fast ions and should it?

We don't often use NBCD (neutral beam current drive) in Process these days, since it is not included in the STEP or EU-DEMO scenarios.

We don't understand the bootstrap current model in PROCESS anyway, and we may replace it with the one proposed by Sakai et al in #954:
> We created a fitting database for the $f_{BS}$ using the ACCOME code.  In this study, equilibria with the fully non-inductively driven conditions with neutral beam (NB) injection only are calculated, where the total plasma current is sustained by NB driven current together with the bootstrap current and the diamagnetic current. Note that the toroidal component of the diamagnetic current $I_{DI}$ was included in $f_{BS}$ in our fitting database; $f_{BS} = (I_{BS} + I_{DI})/I_P$.

The same question will arise - how does ACCOME divide up the current between bootstrap and beam-driven fractions?  

Note that Sakai does not include alphas or helium ions at all - the only impurity is carbon.

**Comment by mkovari** [comment]
No replies so I will close the issue.
