### ISSUE TITLE
Improved HTS models

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#969]
In GitLab by @mkovari on Dec 3, 2019, 15:17

REBCO superconductors have rather gradual superconducting transitions - in other words, the value of *n*, the power law exponent in the IV curve of the superconducting transition has a rather small value - of the order of 25, rather than 45 for LTS. (A low value of the exponent *n* corresponds to a shallow and broad transition, while a high value of the exponent n gives a sudden transition.) This leads to a non-zero electric field near the transition temperature, due to flux creep, giving non-zero joule heating in the superconductor.  

$`(V/V_0)=(I/I_c)^n`$,  
where V is the electric field (loosely the voltage), $`V_0`$ is the electric field criterion (usually taken as 100 µV/m), and $`I_c`$ is the critical current - defined as the current at which the electric field criterion is reached.

For example, in ITER, with LTS coils, the maximum allowable electrical field at the operating temperature is taken as 2 µV/m (to limit cryogenic heat loads).   

To keep the electric field to 2 µV/m when $`n=25`$ requires the current to be 85.5% of $`I_c`$ or less, even before any other factors or margins are taken into account: 
```math
0.855^{25}=\frac{2 \mu V/m}{100  \mu V/m}
```

In any sensible operating conditions this joule heating will be much less than the nuclear heating in a reactor.  However, to be on the safe side, it would be worth including it in the calculation of the power deposited in the cold mass, and especially in any calculation of the cooling circuits of the superconducting coils.

Any volunteers, @schislet @jlion ?

## Checklist

After implementing issue do the following

* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created

**Comment by mkovari** [comment]
Reply from Stuart Wimbush:

I think it makes sense in broad terms. I could provide a line by line criticism if needed (for example if you want to publish) but the overall thrust agrees with my thinking. 
 
I would add that HTS coils (rather than wires) almost always exhibit lower n-values, down as far as 5, but preferably 10-15.
 
I think this heating is always negligible (in every context, not just fusion). This is because no-one would design a magnet to operate at 100% (or even 85%) of Ic. A 50% margin would be typical. Even in cases where I've designed magnets to operate "on the edge", due to the material anisotropy, it is only a tiny fraction of the coil that is at 100% of Ic, so correspondingly only a small region that is generating any heat.
 
In practice, a coil Ic would never be measured with (or operated to) a 1 uV/cm electric field criterion because that would be infeasibly large along the full length of the wire. So this limitation reduces the heating again.

**Comment by mkovari** [comment]
I don't really agree with Stuart's comment that this heating is always negligible.  For example:

Exponent |   |   | Electric field criterion | Electric field | Current | Power per unit length | Length | Power
-- | -- | -- | -- | -- | -- | -- | -- | --
n | I/Ic | V/V0 | V0 (µV/m) | V (µV/m) | I (A) | P=VI (W/m) | L (m) | (W)
10 | 0.5 | 9.77E-04 | 100 | 0.10 | 1.0E+05 | 9.8E-03 | 1.0E+04 | 98

The 98 W is probably negligible in the fusion context.

The electric field criterion is not used to design the magnet, but just to define the critical current.
